"""add_indexes_question_drive_id_studentresponse_student_id_drive_id

Revision ID: 2fc001c425a8
Revises: 5ed1a9dc0b5a
Create Date: 2026-03-05 00:57:33.619414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fc001c425a8'
down_revision: Union[str, None] = '5ed1a9dc0b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop legacy tables only if they exist (may not exist on fresh deployments)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    if 'violation_logs' in existing_tables:
        op.drop_index('ix_violation_logs_id', table_name='violation_logs')
        op.drop_table('violation_logs')
    if 'exam_snapshots' in existing_tables:
        op.drop_index('ix_exam_snapshots_id', table_name='exam_snapshots')
        op.drop_table('exam_snapshots')
    # Drop legacy violation threshold columns from drives only if they exist
    drives_columns = [col['name'] for col in inspector.get_columns('drives')]
    if 'screenshot_threshold' in drives_columns:
        op.drop_column('drives', 'screenshot_threshold')
    if 'tab_switch_threshold' in drives_columns:
        op.drop_column('drives', 'tab_switch_threshold')
    if 'fullscreen_exit_threshold' in drives_columns:
        op.drop_column('drives', 'fullscreen_exit_threshold')
    if 'paste_threshold' in drives_columns:
        op.drop_column('drives', 'paste_threshold')
    if 'copy_threshold' in drives_columns:
        op.drop_column('drives', 'copy_threshold')
    if 'right_click_threshold' in drives_columns:
        op.drop_column('drives', 'right_click_threshold')
    op.create_index(op.f('ix_questions_drive_id'), 'questions', ['drive_id'], unique=False)
    op.create_index(op.f('ix_student_responses_drive_id'), 'student_responses', ['drive_id'], unique=False)
    op.create_index(op.f('ix_student_responses_student_id'), 'student_responses', ['student_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_responses_student_id'), table_name='student_responses')
    op.drop_index(op.f('ix_student_responses_drive_id'), table_name='student_responses')
    op.drop_index(op.f('ix_questions_drive_id'), table_name='questions')
    op.add_column('drives', sa.Column('right_click_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('copy_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('paste_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('fullscreen_exit_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('tab_switch_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('screenshot_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('exam_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drive_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], name='exam_snapshots_drive_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='exam_snapshots_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exam_snapshots_pkey')
    )
    op.create_index('ix_exam_snapshots_id', 'exam_snapshots', ['id'], unique=False)
    op.create_table('violation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drive_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('violation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], name='violation_logs_drive_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='violation_logs_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='violation_logs_pkey')
    )
    op.create_index('ix_violation_logs_id', 'violation_logs', ['id'], unique=False)
    # ### end Alembic commands ###
