"""add_violation_thresholds_to_drives

Revision ID: 5ed1a9dc0b5a
Revises: 9b40e3979345
Create Date: 2026-03-02 16:54:24.827489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed1a9dc0b5a'
down_revision: Union[str, None] = '9b40e3979345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('tab_switch_threshold', sa.Integer(), nullable=True))
    op.add_column('drives', sa.Column('fullscreen_exit_threshold', sa.Integer(), nullable=True))
    op.add_column('drives', sa.Column('right_click_threshold', sa.Integer(), nullable=True))
    op.add_column('drives', sa.Column('screenshot_threshold', sa.Integer(), nullable=True))
    op.add_column('drives', sa.Column('copy_threshold', sa.Integer(), nullable=True))
    op.add_column('drives', sa.Column('paste_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'paste_threshold')
    op.drop_column('drives', 'copy_threshold')
    op.drop_column('drives', 'screenshot_threshold')
    op.drop_column('drives', 'right_click_threshold')
    op.drop_column('drives', 'fullscreen_exit_threshold')
    op.drop_column('drives', 'tab_switch_threshold')
    # ### end Alembic commands ###
